### PR TITLE
Expect grpcwebproxy-grpcWebText to succeed

### PR DESCRIPTION
**Pull request by johanbrandhorst**
This passed on master

Part of #13

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
:thinking: I will try to add some more logging to the tests, would be nice to see why it's erroring.

**Comment by johanbrandhorst** [comment]
:thinking: I will try to add some more logging to the tests, would be nice to see why it's erroring.

**Comment by johanbrandhorst** [comment]
I've rerun the job 7 times without a success, and somehow it succeeded on master: https://circleci.com/gh/johanbrandhorst/grpc-web-compatibility-test/12

**Comment by public** [comment]
The test fails due to timeout which makes me think it might be related to something like this https://github.com/grpc/grpc-web/issues/344 where the browser isn't triggering the callback until it thinks it's got all the data or something.

**Comment by public** [comment]
I can get this test to pass locally but it's flaky. Probably passes less than 1 in 10 times.

**Comment by johanbrandhorst** [comment]
Thanks @public, not sure where that leaves us though. I haven't had a chance to run it manually, does this also happen when, say, a user visits a web page? Might be worth raising an issue over. Presumably this flakiness is also the reason for #13 altogether.

**Comment by public** [comment]
Agree re #13. Running in real non-headless Chrome it also fails. The specific exception it fails on is 

```
index.js:44 Uncaught TypeError: b.i is not a function
    at S.<anonymous> (index.js:44)
    at sb (index.js:29)
    at L (index.js:28)
    at Zb (index.js:37)
    at S../node_modules/grpc-web/index.js.S.R (index.js:36)
    at S../node_modules/grpc-web/index.js.S.K (index.js:36)
```

Unfortunately grpc-web ship a minified JS package in NPM which doesn't help with debugging here. 

I've also tried this in Firefox and it's worked fine the 5ish times I ran it.

**Comment by johanbrandhorst** [comment]
The trailers in the spec are only required if you can't return them the first time you write on the wire. For early-errors they're supposed to be normal headers in the response.

**Comment by johanbrandhorst** [comment]
I think we should raise an issue for this. Seems to be affecting the gRPC/grpc-web client quite a lot?

**Comment by public** [comment]
Yeah let's take the discussion to their issue tracker :)

**Comment by johanbrandhorst** [comment]
I'm gonna close this PR for now, as it is far to flaky to enable.

**Pull request closed without merging**
